"""Add updated_at to alerts for severity escalation tracking

Revision ID: 9db3f3e15b93
Revises: f94e8cfe2011
Create Date: 2026-07-27 09:10:35.757871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db3f3e15b93'
down_revision = 'f94e8cfe2011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
